name: Check Commit Messages
on:
  pull_request:
    branches:
      - main

env:
  BUMPS: "major minor patch"
  COMPONENTS: "lega-commander e2eTests clearinghouse crypt4gh tsd-file-api-client cega-mock localega-tsd-proxy mq-interceptor tsd-api-mock FEGA-Norway"

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    env:
      BASE_REF: ${{ github.event.pull_request.base.ref }}
      HEAD_REF: ${{ github.head_ref }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Find commit messages with bumps
        id: check-commit-messages
        run: |
          read -r -a bumps <<< "$BUMPS"
          bumps_pattern=$(IFS='|'; echo "${bumps[*]}")
          all_matches=$(git log origin/"$BASE_REF"..origin/"$HEAD_REF" --pretty=format:"%s" | grep -oE "#(${bumps_pattern})_[^ ]*" || true)
          {
            echo "all_matches<<EOF"
            echo "$all_matches"
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Check matches in component names
        id: check-match
        if: steps.check-commit-messages.outputs.all_matches != ''
        run: |
          echo "${{ steps.check-commit-messages.outputs.all_matches }}"
          read -r -a components <<< "$COMPONENTS"
          read -r -a bumps <<< "$BUMPS"
          bumps_pattern=$(IFS='|'; echo "${bumps[*]}")
          components_pattern=$(IFS='|'; echo "${components[*]}")
          pattern="#(${bumps_pattern})_(${components_pattern})$"
          all=$(echo "${{ steps.check-commit-messages.outputs.all_matches }}" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
          wrong=$(echo "$all" | grep -Ev "$pattern" || true)
          valid=$(echo "$all" | grep -E "$pattern" || true)

          {
            echo "wrong_matches<<EOF"
            echo "$wrong"
            echo "EOF"
            echo "valid_matches<<EOF"
            echo "$valid"
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Available matches
        if: steps.check-match.outputs.valid_matches != ''
        run: |
          echo "Valid commit messages found:"
          echo "${{ steps.check-match.outputs.valid_matches }}"

      - name: Fail if typos found
        if: steps.check-match.outputs.wrong_matches != ''
        run: |
          echo "Typos found in commit messages:"
          echo "${{ steps.check-match.outputs.wrong_matches }}"
          exit 1